local username = os.getenv("USER") or os.getenv("USERNAME") or "unknown"
local dir = "/tmp/zathura_dynamic." .. username
local rc_path = dir .. "/zathurarc"
local default_conf_dir = "/home/"..username.."/.config/zathura"

local function get_zathura_pid()
  return vim.api.nvim_eval("b:vimtex.viewer.get_pid()")
end

local function hex_to_rgb(hex)
  if not hex then return nil end
  local r = bit.rshift(bit.band(hex, 0xFF0000), 16)
  local g = bit.rshift(bit.band(hex, 0x00FF00), 8)
  local b = bit.band(hex, 0x0000FF)
  return r, g, b
end

local function hl_generic(zathura_name, vim_color, alpha)
  local r, g, b = hex_to_rgb(vim_color)
  if alpha == nil then
    alpha = 1
  end
  if r == nil or g == nil or b == nil then
    print("Can't find color for '" .. zathura_name .. "'")
  end
  return "set "..zathura_name.." rgba("..r..","..g..","..b..","..alpha..")\n"
end

local function hl_fg(zathura_name, vim_name, alpha)
  local color = vim.api.nvim_get_hl(0, {name = vim_name}).fg
  if color == nil then
    color = vim.api.nvim_get_hl(0, {name = "Normal"}).fg
  end
  if color == nil then
    color = 0xFFFFFF
  end
  return hl_generic(zathura_name, color, alpha)
end

local function hl_bg(zathura_name, vim_name, alpha)
  local color = vim.api.nvim_get_hl(0, {name = vim_name}).bg
  if color == nil then
    color = vim.api.nvim_get_hl(0, {name = "Normal"}).bg
  end
  if color == nil then
    color = 0x000000
  end
  return hl_generic(zathura_name, color, alpha)
end

local default_scheme = vim.g.colors_name
local last_scheme = default_scheme

local function sync_colorscheme()
  local pid = get_zathura_pid()
  if pid == 0 or pid == nil then
    return
  end

  local scheme = vim.g.colors_name

  if scheme == last_scheme then
    return
  end

  last_scheme = scheme

  ---@diagnostic disable-next-line: param-type-mismatch
  vim.fn.mkdir(dir, "p", 448) -- 0700

  local f = assert(io.open(rc_path, "w"), "failed to open temp zathura config file")
  f:write("# autogenerated by ~/.config/nvim/ftplugin/tex.lua\n")
  f:write("include "..default_conf_dir.."/zathurarc\n")

  if scheme:find("^catppuccin-") ~= nil then
    f:write("include "..default_conf_dir.."/themes/"..scheme.."\n")
  else
    local lines = {
      hl_fg("default-fg", "Normal"),
      hl_bg("default-bg", "Normal"),
      hl_fg("completion-fg", "Pmenu"),
      hl_bg("completion-bg", "Pmenu"),
      hl_fg("completion-highlight-fg", "PmenuSel"),
      hl_bg("completion-highlight-bg", "PmenuSel"),
      hl_fg("completion-group-fg", "NormalFloat"),
      hl_bg("completion-group-bg", "NormalFloat"),
      hl_fg("statusbar-fg", "StatusLine"),
      hl_bg("statusbar-bg", "StatusLine"),
      hl_fg("inputbar-fg", "Normal"),
      hl_bg("inputbar-bg", "Normal"),
      hl_fg("notification-fg", "Normal"),
      hl_bg("notification-bg", "Normal"),
      hl_fg("notification-error-fg", "ErrorMsg"),
      hl_bg("notification-error-bg", "ErrorMsg"),
      hl_fg("notification-warning-fg", "WarningMsg"),
      hl_bg("notification-warning-bg", "WarningMsg"),
      hl_bg("recolor-lightcolor", "Normal"),
      hl_fg("recolor-darkcolor", "Normal"),
      hl_fg("index-fg", "Normal"),
      hl_bg("index-bg", "Normal"),
      hl_fg("index-active-fg", "PmenuSel"),
      hl_bg("index-active-bg", "PmenuSel"),
      hl_fg("render-loading-fg", "Normal"),
      hl_bg("render-loading-bg", "Normal"),
      hl_bg("highlight-color", "Search", 0.3),
      hl_fg("highlight-fg", "Search"),
      hl_bg("highlight-active-color", "CurSearch", 0.3)
    }

    for _, line in ipairs(lines) do
      f:write(line)
    end
  end

  f:close()

  vim.system({
    "gdbus", "call",
    "--session",
    "--dest", "org.pwmt.zathura.PID-"..pid,
    "--object-path", "/org/pwmt/zathura",
    "--method", "org.pwmt.zathura.SourceConfigFromDirectory",
    dir
  })
end

vim.api.nvim_create_autocmd("ColorScheme", {
  callback = sync_colorscheme
})

vim.api.nvim_create_autocmd("User", {
  pattern = "VimtexEventView",
  callback = function()
    last_scheme = default_scheme

    ---@diagnostic disable-next-line: undefined-field
    local timer = vim.uv.new_timer()
    timer:start(200, 0, vim.schedule_wrap(sync_colorscheme))
  end
})

vim.cmd([[
set textwidth   =90
set colorcolumn =+0
]])
